CREATE TABLE [dbo].[TB_STD_REQUEST_STATUS_ROUTE_INFO] (
    [RequestCode]      CHAR (2) NOT NULL,
    [EventCode]        CHAR (2) NOT NULL,
    [NextStatusCode]   CHAR (2) NULL,
    [CreationUserId]   INT      NOT NULL,
    [CreationDateTime] DATETIME NOT NULL,
    CONSTRAINT [PK_TB_STD_REQUEST_STATUS_ROUTE_INFO] PRIMARY KEY CLUSTERED ([RequestCode] ASC, [EventCode] ASC),
    CONSTRAINT [FK_TB_STD_REQUEST_STATUS_ROUTE_INFO_TB_STD_EVENT_CODE_EventCode] FOREIGN KEY ([EventCode]) REFERENCES [dbo].[TB_STD_EVENT_CODE] ([EventCode]) ON DELETE CASCADE,
    CONSTRAINT [FK_TB_STD_REQUEST_STATUS_ROUTE_INFO_TB_STD_REQUEST_STATUS_CODE_NextStatusCode] FOREIGN KEY ([NextStatusCode]) REFERENCES [dbo].[TB_STD_REQUEST_STATUS_CODE] ([RequestStatusCode]),
    CONSTRAINT [FK_TB_STD_REQUEST_STATUS_ROUTE_INFO_TB_STD_REQUEST_CODE_RequestCode] FOREIGN KEY ([RequestCode]) REFERENCES [dbo].[TB_STD_REQUEST_CODE] ([RequestCode]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_TB_STD_REQUEST_STATUS_ROUTE_INFO_EventCode]
    ON [dbo].[TB_STD_REQUEST_STATUS_ROUTE_INFO]([EventCode] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_TB_STD_REQUEST_STATUS_ROUTE_INFO_NextStatusCode]
    ON [dbo].[TB_STD_REQUEST_STATUS_ROUTE_INFO]([NextStatusCode] ASC);

