CREATE TABLE [dbo].[TB_USER_PASSBOOK] (
    [RequestNo]        VARCHAR (15) NOT NULL,
    [EventCode]        CHAR (2)     NOT NULL,
    [UserId]           INT          NOT NULL,
    [Amount]           INT          NOT NULL,
    [CreationDateTime] DATETIME     NOT NULL,
    CONSTRAINT [PK_TB_USER_PASSBOOK] PRIMARY KEY CLUSTERED ([RequestNo] ASC, [EventCode] ASC),
    CONSTRAINT [FK_TB_USER_PASSBOOK_TB_STD_EVENT_CODE_EventCode] FOREIGN KEY ([EventCode]) REFERENCES [dbo].[TB_STD_EVENT_CODE] ([EventCode]) ON DELETE CASCADE,
    CONSTRAINT [FK_TB_USER_PASSBOOK_TB_REQ_MASTERS_RequestNo] FOREIGN KEY ([RequestNo]) REFERENCES [dbo].[TB_REQ_MASTERS] ([RequestNo]) ON DELETE CASCADE,
    CONSTRAINT [FK_TB_USER_PASSBOOK_AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_TB_USER_PASSBOOK_EventCode]
    ON [dbo].[TB_USER_PASSBOOK]([EventCode] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_TB_USER_PASSBOOK_UserId]
    ON [dbo].[TB_USER_PASSBOOK]([UserId] ASC);

